spring:
  datasource:
    url: ${TODO_DB_URL}
    username: ${TODO_DB_USERNAME}
    password: ${TODO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # SMTP SERVER
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.debug: true

  # Twilio configuration
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    phone-number: ${TWILIO_PHONE_NUMBER}


  # Rabbit MQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}


# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    fetch-registry: true



# Actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh


server:
  port: 6062
